stages:
  - build
  - s3_upload

build:
  stage: build
  allow_failure: false
  only:
    - main
    - tags
  tags:
    - randstad-bluex
  script: |
    git remote add codecommit /fake-temp-url || true
    
    # DF account
    git remote set-url codecommit https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/git-df-prd-bluex-lib-react-components
    AWS_PROFILE="bluex-codecommit" git push codecommit HEAD:refs/heads/$CI_COMMIT_REF_NAME
    
    # Bluex account
    git remote set-url codecommit https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/git-bluex-prd-bx-lib-react-components
    git push codecommit HEAD:refs/heads/$CI_COMMIT_REF_NAME

local_translations_upload:
  stage: s3_upload
  allow_failure: false
  rules:
    - if: $environment != null &&  $CI_PIPELINE_SOURCE == "pipeline"
  script: |
    echo "Translations uploaded for "
    echo $ENVIRONMENT
