stages:
  - build
  - translations_upload
  - test

merge_request_test:
  stage: test
  allow_failure: true
  only:
    - merge_requests
  tags:
    - randstad-bluex
  script: |
    echo Testing.
    nvm use 18
    stat node_modules yarn install
    yarn test --coverage
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/clover.xml

build:
  stage: build
  allow_failure: false
  tags:
    - randstad-bluex
  # Execute for "main" branch and all tags, and do not execute when triggered externally.
  rules:
    - if: $ENVIRONMENT == null && $CI_PIPELINE_SOURCE != "pipeline" && ($CI_COMMIT_BRANCH == "main" || $CI_COMMIT_TAG)
  script: |
    git remote add codecommit /fake-temp-url || true
    
    # DF account
    git remote set-url codecommit https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/git-df-prd-bluex-lib-react-components
    AWS_PROFILE="bluex-codecommit" git push codecommit HEAD:refs/heads/$CI_COMMIT_REF_NAME
    
    # Bluex account
    git remote set-url codecommit https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/git-bluex-prd-bx-lib-react-components
    git push codecommit HEAD:refs/heads/$CI_COMMIT_REF_NAME

translations_upload:
  stage: translations_upload
  allow_failure: false
  tags:
    - randstad-bluex
  # Execute when externally triggered only.
  rules:
    - if: $ENVIRONMENT && $CI_PIPELINE_SOURCE == "pipeline"
  script: |
    
    # s3-sync is the aws s3 profile used for the dev environments
    AWS_S3_PROFILE="s3-sync"
    
    if [[ $ENVIRONMENT == "test" ]]; then
      ENVIRONMENT="tst";
    fi
    
    if [[ $ENVIRONMENT == "prod" ]]; then
      ENVIRONMENT="prd";
    fi
    set -x
    AWS_PROFILE="$AWS_S3_PROFILE" aws s3 sync src/i18n/ s3://s3-bluex-dta-bx-${ENVIRONMENT}2-localization/components_lib/default/ --include "??.json" --grants full=id=9ad45dfc00439d89906f4ac4321f9cfc63a061e60782b351ca166be4a29ba2d2,id=c39407c258b649c24787709e277f4d48507596dcf9b9b57e0857222f678446f3
