stages:
  - build
  - translations_upload

build:
  stage: build
  allow_failure: false
  tags:
    - randstad-bluex
  # Execute for "main" branch and all tags, and do not execute when triggered externally.
  rules:
    - if: $ENVIRONMENT == null && $CI_PIPELINE_SOURCE != "pipeline" && ($CI_COMMIT_BRANCH == "main" || $CI_COMMIT_TAG)
  script: |
    git remote add codecommit /fake-temp-url || true
    
    # DF account
    git remote set-url codecommit https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/git-df-prd-bluex-lib-react-components
    AWS_PROFILE="bluex-codecommit" git push codecommit HEAD:refs/heads/$CI_COMMIT_REF_NAME
    
    # Bluex account
    git remote set-url codecommit https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/git-bluex-prd-bx-lib-react-components
    git push codecommit HEAD:refs/heads/$CI_COMMIT_REF_NAME

translations_upload:
  stage: translations_upload
  allow_failure: false
  tags:
    - randstad-bluex
  # Execute when externally triggered only.
  rules:
    - if: $environment && $CI_PIPELINE_SOURCE == "pipeline"
  script: |
    set -x
    aws s3 sync src/i18n/ s3://s3-bluex-dta-bx-${environment}2-localization/components_lib/default/ --exclude "*" --include "??.json"
