const fetchAsset = require("./fetchAsset");
const packageConf = require("../../package.json");

fetchAsset(
  "https://RandstadWeb:RXPPlatform!2022@uk-static-dev.dta.randstadbluex.com/themes/custom/bluex/dist/assets/image/icons.svg",
  "autogenerated-icons.svg",
);

packageConf.orbitLibraries.forEach((lib) =>
  fetchAsset(
    `https://RandstadWeb:RXPPlatform!2022@uk-static-dev.dta.randstadbluex.com/articles/static/assets/js/imports/${lib}.js`,
    `${lib}.js`,
  ),
);
