const changeSVGPath = (use: Element) => {
  const SVG_XLINK = "http://www.w3.org/1999/xlink";

  const svgPath = !window.location.href.includes("localhost")
    ? "/build/assets"
    : "/src/docs-lib/assets";

  const newPath = use?.getAttribute("xlink:href")?.replace(
    "/themes/custom/bluex/dist/assets/image/icons.svg",
    svgPath + "/autogenerated-icons.svg",
  );

  newPath && use.setAttributeNS(SVG_XLINK, "xlink:href", newPath);
};

export default function load() {
  const observerConfig = {
    childList: true,
    subtree: true,
  };

  var observer = new MutationObserver(function (mutations) {
    mutations.forEach(function (mutation) {
      for (var i = 0; i < mutation.addedNodes.length; i++) {
        if (!(mutation.addedNodes[i] instanceof HTMLElement)) {
          continue;
        }
        
        const use = (mutation.addedNodes[i] as HTMLElement).querySelectorAll(
          "[data-testid='mountNode'] .icon > svg use",
        );

        if (use["0"] && use["0"].getAttribute("xlink:href")?.includes("themes")) {
          use.forEach((i) => changeSVGPath(i));
        }
      }
    });
  });

  const mainContent = document.querySelector("main.rsg--content-3");

  if (mainContent !== null) {
    observer.observe(mainContent, observerConfig);
  } else {
    console.error("Could not find main.rsg--content-3");
  }
}
