import React from "react";

interface Svg {
  icon: string
}

const Svg = ({ icon }: Svg) => {

  const svgPath = !process.env.NEXT_PUBLIC_RESOURCE_PREFIX ? <use xlinkHref={`/src/docs-lib/assets/autogenerated-icons.svg#${icon}`} /> : <use xlinkHref={`${process.env.NEXT_PUBLIC_RESOURCE_PREFIX}/src/assets/img/icons.svg#${icon}`} />;

  return (
    <svg>
      {svgPath}
    </svg>
  );
};

export default Svg;
